version: '3.9'

services:
  db-postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data

  pgadmin:
    image: elestio/pgadmin:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_USER
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_PASSWORD
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - 8080:8080
    volumes:
      - ./postgresql/pgadmin:/pgadmin

  db-mssql:
    image: mcr.microsoft.com/mssql/server:latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: $MSSQL_PASSWORD
    ports:
      - "1433:1433"
    volumes:
      - ./mssql/data:/var/opt/mssql

networks:
  default:
    name: local-network
    external: true
