-- Role: services
-- DROP ROLE IF EXISTS services;

CREATE ROLE services WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  NOBYPASSRLS
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:OPZ7LbMaiPWMP0sKSxsLnQ==$2J5TGf0fYIR//uyAIUj33sA0UO1J3Dr/H8qi+RSUrck=:iUJkz0HWfE5pBeOIdTdMYptmRBxGXZrOcj/WrOjhfbk=';
